version: '3.9'

services:

  code-labo-mysql-large-num-records:
    # build: .
    image: mysql:8.0.28-debian       # https://hub.docker.com/_/mysql
    container_name: code-labo-mysql-large-num-records
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 0123456789abcd
    # ports:
    #   - "127.0.0.1:13306:3306"
    volumes:
      - ./mount:/mnt/
      # - ./mysql/files/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - code-labo

networks:
  code-labo:
    driver: bridge
